//
// Generated file, do not edit! Created by opp_msgtool 6.2 from src/LCCMessage.msg.
//

#ifndef __INET_LCCMESSAGE_M_H
#define __INET_LCCMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0602
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace inet {

class LccBeacon;
class LccData;

}  // namespace inet

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk


namespace inet {

/**
 * Enum generated from <tt>src/LCCMessage.msg:7</tt> by opp_msgtool.
 * <pre>
 * enum LccRole
 * {
 *     UNDECIDED = 0;
 *     CLUSTER_MEMBER = 1;
 *     CLUSTER_HEAD = 2;
 * }
 * </pre>
 */
enum LccRole {
    UNDECIDED = 0,
    CLUSTER_MEMBER = 1,
    CLUSTER_HEAD = 2
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const LccRole& e) { b->pack(static_cast<int>(e)); }
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, LccRole& e) { int n; b->unpack(n); e = static_cast<LccRole>(n); }

/**
 * Class generated from <tt>src/LCCMessage.msg:14</tt> by opp_msgtool.
 * <pre>
 * // 1. Yönetim Paketi (Beacon)
 * class LccBeacon extends FieldsChunk
 * {
 *     int srcId;
 *     int role \@enum(LccRole);
 *     int clusterHeadId;
 * }
 * </pre>
 */
class LccBeacon : public ::inet::FieldsChunk
{
  protected:
    int srcId = 0;
    int role = 0;
    int clusterHeadId = 0;

  private:
    void copy(const LccBeacon& other);

  protected:
    bool operator==(const LccBeacon&) = delete;

  public:
    LccBeacon();
    LccBeacon(const LccBeacon& other);
    virtual ~LccBeacon();
    LccBeacon& operator=(const LccBeacon& other);
    virtual LccBeacon *dup() const override {return new LccBeacon(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getSrcId() const;
    virtual void setSrcId(int srcId);

    virtual int getRole() const;
    virtual void setRole(int role);

    virtual int getClusterHeadId() const;
    virtual void setClusterHeadId(int clusterHeadId);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const LccBeacon& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, LccBeacon& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>src/LCCMessage.msg:21</tt> by opp_msgtool.
 * <pre>
 * // 2. Veri Paketi (YENİ - İstatistikler için)
 * class LccData extends FieldsChunk
 * {
 *     int srcId;
 *     int destId;
 *     simtime_t sendTime; // Gecikme ölçmek için
 *     int sequenceNumber;
 * }
 * </pre>
 */
class LccData : public ::inet::FieldsChunk
{
  protected:
    int srcId = 0;
    int destId = 0;
    ::omnetpp::simtime_t sendTime = SIMTIME_ZERO;
    int sequenceNumber = 0;

  private:
    void copy(const LccData& other);

  protected:
    bool operator==(const LccData&) = delete;

  public:
    LccData();
    LccData(const LccData& other);
    virtual ~LccData();
    LccData& operator=(const LccData& other);
    virtual LccData *dup() const override {return new LccData(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getSrcId() const;
    virtual void setSrcId(int srcId);

    virtual int getDestId() const;
    virtual void setDestId(int destId);

    virtual ::omnetpp::simtime_t getSendTime() const;
    virtual void setSendTime(::omnetpp::simtime_t sendTime);

    virtual int getSequenceNumber() const;
    virtual void setSequenceNumber(int sequenceNumber);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const LccData& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, LccData& obj) {obj.parsimUnpack(b);}


}  // namespace inet


namespace omnetpp {

template<> inline inet::LccBeacon *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::LccBeacon*>(ptr.get<cObject>()); }
template<> inline inet::LccData *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::LccData*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __INET_LCCMESSAGE_M_H

